### ISSUE TITLE
Difference to /std lib

### ISSUE THREAD

**Issue by KnorpelSenf** [worker-tools/resolvable-promise#1]
There is already https://doc.deno.land/https://deno.land/std@0.135.0/async/deferred.ts in the standard library of Deno. Is there any difference to what this project is trying to do?

**Comment by qwtel** [comment]
Oh, I wasn't aware. Technically, this one is even a bit worse because it is `PromiseLike`, not an actual subclass of `Promise`. 

I've recently converted most of worker-tools to Deno, so I'm just publishing what's already there.
